### ISSUE TITLE
When is state storage initiated?

### ISSUE THREAD

**Issue by dennari** [hubotio/hubot-redis-brain#15]
Since the autosave is turned off, I guess the only time the state is saved is when the `robot.shutdown` method is called. I'm wondering, since I'm unable to see any content in my redis.

**Comment by nanaeasiedu** [comment]
@dennari The `autosave` is turned off [temporarily](https://github.com/hubot-scripts/hubot-redis-brain/blob/master/src%2Fredis-brain.coffee#L41) and turned [back on](https://github.com/hubot-scripts/hubot-redis-brain/blob/master/src%2Fredis-brain.coffee#L54) again after there a connection to redis is established.

The state is saved anytime the brain emits [`save`](https://github.com/hubot-scripts/hubot-redis-brain/blob/master/src%2Fredis-brain.coffee#L74) event.

**Comment by mose** [comment]
Great answer @ngenerio :)
