### ISSUE TITLE
On Connect Event

### ISSUE THREAD

**Issue by wevanscfi** [hubotio/hubot-redis-brain#17]
I was recently looking for a good event to be able to tie into during hubot start up for actions that require values from redis. It looks like the on load event for robot.brain is also called anytime a value is set, so I would suggest emitting "connected" event or similar once redis brain is ready to read/write values on start up.

**Comment by mose** [comment]
The PR #20 was merged, so there is the `connected` event available at redis connection, in more of the hubot internal `loaded` event from brain.
