### ISSUE TITLE
redis.brain acts different on local redis server compared to heroku redis cloud.

### ISSUE THREAD

**Issue by auryn-macmillan** [hubotio/hubot-redis-brain#21]
Posted issue here originally: https://github.com/github/hubot-scripts/issues/1712

**Comment by mose** [comment]
> I wrote a script for automating responses on slack, it works great using a local redis server, but when I run it on heroku using the redis cloud some of the logic doesn't work. Any idea what might cause this?
> 
> Here's a link to my script: https://github.com/auryn-macmillan/spam_free_slackbot/blob/master/src/spam-free-slackbot.coffee#L157

@auryn-macmillan can you specify what is the difference in logic that you talk about? Can you provide some output?

I updated the version of the `redis` package on the master branch, maybe it would make sense to try again (but you would need to use the `hubot-redis-brain` from the repo, it's not packaged yet).

**Comment by auryn-macmillan** [comment]
@mose I'm no longer working on the project that was utilizing this. But if I get some spare time I'll try it out and report back.
