### ISSUE TITLE
hubot not responding to redis

### ISSUE THREAD

**Issue by jy2008** [hubotio/hubot-redis-brain#22]
my hubot rocket.chat adapter works well except for every time i started hubot, I had to reset the following items:

```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
export HUBOT_YOUTUBE_API_KEY=<your token>
```

I get the feel hubot is not really responding to redis that i installed. I do have `hubot-redis-brain` installed as well. Is there any other setting I need to do in order to make it work? Or should i just re-install the whole thing? what might be the possible reason?

**Comment by technicalpickles** [comment]
Do you get any output when you start hubot about redis? There should be an `INFO` line when connected.

Do you have `hubot-redis-brain` installed (can confirm in package.json) and added to `external-scripts.json`?

**Comment by jy2008** [comment]
Yes, i did receive info as below:

```
[Wed Oct 19 2016 02:44:24 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Wed Oct 19 2016 02:44:24 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
```

so looks like it does connects to redis. right? then why every time when i started hubot, i have to do the following first before `bin/hubot -a rocketchat`? Any ideas? I know it might be out of your territory, so thanks very much for your response and let me know if you know anything about this.

```
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot
export ROCKETCHAT_AUTH=password
```

**Comment by technicalpickles** [comment]
> so looks like it does connects to redis. right? 

Yes, it does look that way. Is there something that makes you think it's not loading?

>  Any ideas? I know it might be out of your territory, so thanks very much for your response and let me know if you know anything about this.

It's out of scope of this particular plugin, yeah. It's a more general obstacle for hubot users. Basically, there isn't a canonical way to do it, but you need some way of adding it to the environment. If you could file an issue in github/hubot asking about that, I can try to get you more details and update documentation.

**Comment by jy2008** [comment]
Yes, that is what i am missing, adding it to the environment. I think i am just gonna open an new issue on hubot github, thank you very much for your help. i am off your back now, hehe
