### ISSUE TITLE
How to save hubot info to redis

### ISSUE THREAD

**Issue by jy2008** [hubotio/hubot-redis-brain#23]
I installed redis and hubot-redis-brain, and my hubot is connecting to redis every time it starts. But i still don't know how to save data to redis, none of the hubot info seems to be saved by redis. I haven't set up any variable either. so all i need to do is just `export REDIS_URL=redis://passwd@192.168.0.1:16379/prefix`  ? that will make redis remember all the log in information? any more setup i need to do? what do i need to do to save hubot data to redis? Is there tutorial i can read ?

**Comment by technicalpickles** [comment]
Check out the scripting documentation if you haven't already: https://hubot.github.com/docs/scripting/ 

In particular, the persistence section covers it: https://hubot.github.com/docs/scripting/#persistence

**Comment by jy2008** [comment]
thank you very much for responding!
