### ISSUE TITLE
Does not work inside docker

### ISSUE THREAD

**Issue by danielo515** [hubotio/hubot-redis-brain#32]
Hello,

I am trying to use this module in a hubot that is packed inside a docker container, but it is not working. If I run the bot on my machine (a MacBook Pro) it runs perfectly and connects to redis, however, when I put the same bot inside a docker container it gets a weird error about `_ref.toString` is not a function. This is the only module of the bot that does not work inside a docker container, if I remove it the bot works perfectly inside the docker container.

Thanks in advance

**Comment by dgershman** [comment]
What is `REDIS_URL` pointing to?

**Comment by joeyguerra** [comment]
Stale.
