### ISSUE TITLE
Too much user data

### ISSUE THREAD

**Issue by timothyeburke** [hubotio/hubot-redis-brain#37]
Looking for recommendations:

My work's slack workspace has over 7000 users. As the bot runs for a while, it caches all of those users in the brain, which gets written to and read from Redis. The JSON blob gets up over 10MB, which isn't a lot, but moving that back and forth so much between the bot process and Redis starts taking a lot of time, causing the bot to be sluggish. Is there a way to disable caching the user info in Redis? My current solution is to wipe the brain user cache ever 15 min, but it feels hacky.

**Comment by daniel-beard** [comment]
+1 I am also seeing this issue

**Comment by timothyeburke** [comment]
I just ended up rewriting Hubot and Redis Brain in Golang, and sidestepped this problem by excluding the user data from the brain.

**Comment by daniel-beard** [comment]
@timothyeburke why'd you close this ticket? It's still valid for this project.
