### ISSUE TITLE
Tag 1.0.0 uses vulnerable Redis version

### ISSUE THREAD

**Issue by nwbreneman** [hubotio/hubot-redis-brain#44]
Tag 1.0.0 here and in the npm repository depends on Redis version `^2.7.1`. There is a high severity vulnerability in Redis versions `2.6.0 - 3.1.0` (https://github.com/advisories/GHSA-35q2-47q7-3pc3). I see commit 2ab8963 bumped the Redis dependency version but was not tagged for release; could we tag that to resolve security alerts?

**Comment by scarolan** [comment]
Yes please.  We have the same security alert with our hubot.

**Comment by YulianaPoliakova** [comment]
We have the same issue with our hubot.

**Comment by joeyguerra** [comment]
Checkout the latest version. It's been updated.
