### ISSUE TITLE
Not connecting with redis 4.6.7

### ISSUE THREAD

**Issue by lveraszto** [hubotio/hubot-redis-brain#47]
Hello,

i did some debug, and figured out from the logs that this is currently not working, because it never connects to redis.
The log "hubot-redis-brain: Successfully connected to Redis" is not showing.

According to the redis npm package doc it need to call `await client.connect();`.

I tried it out and it worked, please fix this.

Thanks

**Comment by joeyguerra** [comment]
`hubot-redis-brain` currently uses/depends on `redis@2.7.1`. Not `redis@4.6.7`. As such, `connect` does not exist on the `client` instance.

I tested connecting to Redis with the current release of `hubot-redis-brain` and it connected to a local instance of Redis. I see the log message:

```
[22:47:04.532] INFO (pipbot/16342): hubot-redis-brain: Using default redis on localhost:6379
[22:47:04.539] INFO (pipbot/16342): hubot-redis-brain: Initializing new data for hubot brain
```

However, the `hubot-redis-brain: Successfully connected to Redis` message doesn't get outputted, as you've noted. But the module does appear to work/successfully connect to Redis.

I installed the module with:

```
npm install hubot-redis-brain
```

and I created a file called `external-scripts.json` at the root level of my bot codebase with the following in it:

```json
["hubot-redis-brain"]
```

which installs `redis@2.7.1`. Not `redis@4.6.7`. Please feel free to open another issue if you find additional information/problems.

**Comment by lveraszto** [comment]
Hello

thanks for the answer.

I just double checked it, i see in the `package.json` and package-lock.json` that the redis version is `"redis": "^4.6.6"`.
I downloaded the latest release 1.1.1 and after an `npm i` i checked the versions with `npm ls` and it says:

`hubot-redis-brain-1.1.1
├── chai@4.3.7
├── hubot@3.4.0
├── matchdep@2.0.0
├── mocha@10.2.0
├── nyc@15.1.0
├── redis@4.6.6
├── semantic-release@21.0.2
├── sinon-chai@3.7.0
├── sinon@15.0.4
└── standard@17.1.0`

Thanks

**Comment by joeyguerra** [comment]
Sorry for the confusion. When I tested, I installed `hubot-redis-brain@1.0.0`. I'll reopen this issue and work on updating the codebase to use the latest version of `redis`.

**Comment by joeyguerra** [comment]
@lveraszto please let me know if it works. Closing for now. But will re-open if there's more to do on this.
